#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
generator="$root/scripts/codex-agent-generator.sh"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

failures=0
out="$tmp_dir/out"
err="$tmp_dir/err"

pass() {
  printf 'PASS: %s\n' "$1"
}

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  failures=$((failures + 1))
}

run_expect_pass() {
  local label="$1"
  shift
  if "$@" >"$out" 2>"$err"; then
    pass "$label"
  else
    fail "$label"
    sed -n '1,100p' "$out" >&2 || true
    sed -n '1,100p' "$err" >&2 || true
  fi
}

run_expect_fail() {
  local label="$1" expected="$2"
  shift 2
  if "$@" >"$out" 2>"$err"; then
    fail "$label"
    sed -n '1,100p' "$out" >&2 || true
    return
  fi
  if grep -q "$expected" "$err"; then
    pass "$label"
  else
    fail "$label"
    sed -n '1,100p' "$out" >&2 || true
    sed -n '1,100p' "$err" >&2 || true
  fi
}

dry_run_dir="$tmp_dir/dry-run-output"
run_expect_pass "codex generator dry-run prints plan" \
  "$generator" --output-dir "$dry_run_dir" --dry-run

if grep -q '^CODEX_AGENT_GENERATOR_DRY_RUN=1$' "$out" \
  && grep -q '^REGISTRY_HASH=' "$out" \
  && grep -q 'sfa-harness-reviewer.toml' "$out"; then
  pass "dry-run includes registry hash and reviewer target"
else
  fail "dry-run includes registry hash and reviewer target"
  sed -n '1,100p' "$out" >&2 || true
fi

if [[ ! -e "$dry_run_dir" ]]; then
  pass "dry-run does not write output directory"
else
  fail "dry-run does not write output directory"
fi

apply_dir="$tmp_dir/apply-output"
run_expect_pass "codex generator writes to explicit local output when applied" \
  "$generator" --output-dir "$apply_dir" --apply

reviewer_file="$apply_dir/sfa-harness-reviewer.toml"
if [[ -f "$reviewer_file" ]] \
  && grep -q 'Generated by scripts/codex-agent-generator.sh' "$reviewer_file" \
  && grep -q 'agent_id = "sfa-harness-reviewer"' "$reviewer_file" \
  && grep -q 'reviewer-gate.sh' "$reviewer_file" \
  && grep -q 'output_contract' "$reviewer_file"; then
  pass "generated reviewer config contains provenance and contract"
else
  fail "generated reviewer config contains provenance and contract"
  sed -n '1,120p' "$reviewer_file" >&2 || true
fi

home_dir="$tmp_dir/home"
mkdir -p "$home_dir"
run_expect_fail "global codex agent writes require explicit opt-in" "global output requires --allow-global" \
  env HOME="$home_dir" "$generator" --output-dir "$home_dir/.codex/agents" --apply

before_config_sha="$(cksum "$root/.codex/config.toml" | cut -d' ' -f1-2)"
before_hooks_sha="$(cksum "$root/.codex/hooks.json" | cut -d' ' -f1-2)"
run_expect_pass "codex generator leaves project hooks untouched" \
  "$generator" --output-dir "$tmp_dir/second-apply" --apply
after_config_sha="$(cksum "$root/.codex/config.toml" | cut -d' ' -f1-2)"
after_hooks_sha="$(cksum "$root/.codex/hooks.json" | cut -d' ' -f1-2)"
if [[ "$before_config_sha" == "$after_config_sha" && "$before_hooks_sha" == "$after_hooks_sha" ]]; then
  pass "project codex config and hooks are unchanged"
else
  fail "project codex config and hooks are unchanged"
fi

if [[ "$failures" -gt 0 ]]; then
  printf 'FAIL: codex agent generator test had %s failure(s)\n' "$failures" >&2
  exit 1
fi

printf 'PASS: codex agent generator test passed\n'
