#!/usr/bin/env bash
# Local-only repo mapping for this machine. Do not commit this file.

export SFA_HARNESS_ROOT="${SFA_HARNESS_ROOT:-/Users/00555733/sfa-ai-harness}"
export SFA_PROJECTS_ROOT="${SFA_PROJECTS_ROOT:-/Users/00555733/codex/sfa-projects}"

export SFA_REPO_BACKEND_SALES_MANAGEMENT="${SFA_REPO_BACKEND_SALES_MANAGEMENT:-$SFA_PROJECTS_ROOT/sfa-sales-management}"
export SFA_REPO_BACKEND_SFA_BACKEND="${SFA_REPO_BACKEND_SFA_BACKEND:-$SFA_PROJECTS_ROOT/sfa-backend}"
export SFA_REPO_FRONTEND_MAP_SYSTEM="${SFA_REPO_FRONTEND_MAP_SYSTEM:-$SFA_PROJECTS_ROOT/mapSystem}"
export SFA_REPO_FRONTEND_SIGN_UP="${SFA_REPO_FRONTEND_SIGN_UP:-$SFA_PROJECTS_ROOT/sign-up}"
export SFA_REPO_MOBILE_SFA_IOS="${SFA_REPO_MOBILE_SFA_IOS:-$SFA_PROJECTS_ROOT/sfa-ios}"
export SFA_REPO_MOBILE_SFA_ANDROID="${SFA_REPO_MOBILE_SFA_ANDROID:-$SFA_PROJECTS_ROOT/sfa-android}"

export SFA_BACKEND_MAVEN_COMMAND="${SFA_BACKEND_MAVEN_COMMAND:-mvn}"
export SFA_BACKEND_MAVEN_ARGS="${SFA_BACKEND_MAVEN_ARGS:-}"
export SFA_FRONTEND_PACKAGE_MANAGER="${SFA_FRONTEND_PACKAGE_MANAGER:-npm}"
export SFA_FRONTEND_PACKAGE_MANAGER_ARGS="${SFA_FRONTEND_PACKAGE_MANAGER_ARGS:-}"
export SFA_BACKEND_JAVA_MAJOR="${SFA_BACKEND_JAVA_MAJOR:-8}"
export SFA_FRONTEND_NODE_VERSION="${SFA_FRONTEND_NODE_VERSION:-14.21.3}"

export SFA_PC_E2E_USERNAME="${SFA_PC_E2E_USERNAME:-00441211}"
export SFA_PC_E2E_PASSWORD="${SFA_PC_E2E_PASSWORD:-123456}"

export SFA_HARNESS_SMOKE="${SFA_HARNESS_SMOKE:-0}"
export SFA_HARNESS_PROXY_HOST="${SFA_HARNESS_PROXY_HOST:-127.0.0.1}"
export SFA_HARNESS_PROXY_PORT="${SFA_HARNESS_PROXY_PORT:-19080}"
export SFA_LOCAL_BACKEND_SALES_MANAGEMENT_URL="${SFA_LOCAL_BACKEND_SALES_MANAGEMENT_URL:-http://127.0.0.1:31010}"
export SFA_LOCAL_BACKEND_SFA_BACKEND_URL="${SFA_LOCAL_BACKEND_SFA_BACKEND_URL:-http://127.0.0.1:30080}"

# SIT DB local-only connection. Do not commit or echo secrets.
export SFA_SIT_DB_JDBC_URL="${SFA_SIT_DB_JDBC_URL:-jdbc:mysql://rm-uf6c15st2r698z8130o.mysql.rds.aliyuncs.com:3306/hotkid_sfa_sit?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&noAccessToProcedureBodies=true}"
export SFA_SIT_DB_HOST="${SFA_SIT_DB_HOST:-rm-uf6c15st2r698z8130o.mysql.rds.aliyuncs.com}"
export SFA_SIT_DB_PORT="${SFA_SIT_DB_PORT:-3306}"
export SFA_SIT_DB_NAME="${SFA_SIT_DB_NAME:-hotkid_sfa_sit}"
export SFA_SIT_DB_USERNAME="${SFA_SIT_DB_USERNAME:-sfa_write}"
export SFA_SIT_DB_PASSWORD="${SFA_SIT_DB_PASSWORD:-mh73ea5k@h4B5EX5}"
export SFA_SIT_DB_ACCESS_MODE="${SFA_SIT_DB_ACCESS_MODE:-readonly-by-default}"

export SFA_DECISION_LARK_CHAT="${SFA_DECISION_LARK_CHAT:-}"
