#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
gate="$root/scripts/agent-dispatch-plan-gate.sh"
planner="$root/scripts/agent-dispatch-plan.sh"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

failures=0
out="$tmp_dir/out"
err="$tmp_dir/err"

pass() {
  printf 'PASS: %s\n' "$1"
}

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  failures=$((failures + 1))
}

run_expect_pass() {
  local label="$1"
  shift
  if "$@" >"$out" 2>"$err"; then
    pass "$label"
  else
    fail "$label"
    sed -n '1,120p' "$out" >&2 || true
    sed -n '1,120p' "$err" >&2 || true
  fi
}

run_expect_fail() {
  local label="$1" expected="$2"
  shift 2
  if "$@" >"$out" 2>"$err"; then
    fail "$label"
    sed -n '1,120p' "$out" >&2 || true
    return
  fi
  if grep -q "$expected" "$err"; then
    pass "$label"
  else
    fail "$label"
    sed -n '1,120p' "$out" >&2 || true
    sed -n '1,120p' "$err" >&2 || true
  fi
}

write_candidate_confirmation() {
  local target="$1" allowed_agent_ids="$2" confirmation="${3:-CONFIRMED}"
  cat >"$target" <<MARKDOWN
# Agent Candidate Confirmation: candidate-change

candidate_dispatch_confirmation: $confirmation
change_id: candidate-change
allowed_agent_ids: $allowed_agent_ids
business_code_start_gate: PASS
allowed_paths_confirmed: yes
isolated_worktree_required: yes
protected_actions_allowed: no
global_config_write_allowed: no
db_or_release_actions_allowed: no
confirmed_by: test
confirmed_at: 2026-07-03T00:00:00+08:00
MARKDOWN
}

review_change="$tmp_dir/review-change"
mkdir -p "$review_change"
"$planner" --agent-id sfa-harness-reviewer --runtime codex_generated --change-id review-change --output "$review_change/agent-dispatch-plan.md" >/dev/null
run_expect_pass "dispatch plan gate accepts registry-generated reviewer plan" \
  "$gate" "$review_change"

missing_change="$tmp_dir/missing-change"
mkdir -p "$missing_change"
run_expect_fail "dispatch plan gate blocks missing plan" "missing agent dispatch plan" \
  "$gate" "$missing_change"

broken_change="$tmp_dir/broken-change"
mkdir -p "$broken_change"
cat >"$broken_change/agent-dispatch-plan.md" <<'MARKDOWN'
# Agent Dispatch Plan: broken-change

## missing-agent

agent_id: missing-agent
output_contract: review_findings
required_gates: scripts/reviewer-gate.sh
gate_consumers: scripts/reviewer-gate.sh
MARKDOWN
run_expect_fail "dispatch plan gate blocks unregistered agent" "unregistered agent_id" \
  "$gate" "$broken_change"

candidate_change="$tmp_dir/candidate-change"
mkdir -p "$candidate_change"
candidate_confirmation="$candidate_change/agent-candidate-confirmation.md"
write_candidate_confirmation "$candidate_confirmation" "[sfa-backend-agent,sfa-frontend-agent,sfa-mobile-agent]"
"$planner" --stage implementation_after_contract_v0_1 --runtime codex_generated --allow-candidate --candidate-confirmation "$candidate_confirmation" --change-id candidate-change --output "$candidate_change/agent-dispatch-plan.md" >/dev/null
run_expect_pass "dispatch plan gate accepts explicit candidate opt-in generated by planner" \
  "$gate" "$candidate_change"

unsafe_candidate="$tmp_dir/unsafe-candidate"
mkdir -p "$unsafe_candidate"
cp "$candidate_change/agent-dispatch-plan.md" "$unsafe_candidate/agent-dispatch-plan.md"
sed 's/candidate_dispatch: explicit_opt_in/candidate_dispatch: REQUIRED_BEFORE_DISPATCH/' \
  "$unsafe_candidate/agent-dispatch-plan.md" >"$unsafe_candidate/agent-dispatch-plan.tmp"
mv "$unsafe_candidate/agent-dispatch-plan.tmp" "$unsafe_candidate/agent-dispatch-plan.md"
run_expect_fail "dispatch plan gate blocks candidate without explicit opt-in marker" "candidate agent requires explicit opt-in" \
  "$gate" "$unsafe_candidate"

invalid_candidate="$tmp_dir/invalid-candidate"
mkdir -p "$invalid_candidate"
invalid_confirmation="$invalid_candidate/agent-candidate-confirmation.md"
write_candidate_confirmation "$invalid_confirmation" "[sfa-backend-agent,sfa-frontend-agent,sfa-mobile-agent]" "PENDING"
cp "$candidate_change/agent-dispatch-plan.md" "$invalid_candidate/agent-dispatch-plan.md"
sed "s#candidate_confirmation: $candidate_confirmation#candidate_confirmation: $invalid_confirmation#" \
  "$invalid_candidate/agent-dispatch-plan.md" >"$invalid_candidate/agent-dispatch-plan.tmp"
mv "$invalid_candidate/agent-dispatch-plan.tmp" "$invalid_candidate/agent-dispatch-plan.md"
run_expect_fail "dispatch plan gate blocks unconfirmed candidate evidence" "candidate confirmation" \
  "$gate" "$invalid_candidate"

if [[ "$failures" -gt 0 ]]; then
  printf 'FAIL: agent dispatch plan gate test had %s failure(s)\n' "$failures" >&2
  exit 1
fi

printf 'PASS: agent dispatch plan gate test passed\n'
